name: My Workflow

on: push

jobs:
    env_path_test:
        name: Env and PATH test
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Env vars and PATH test in parent image
            uses: MeterianHQ/meterian-github-action@v1.0.2-canary
            with:
                entrypoint: ./entrypoint.sh