name: Meterian Vulnerability Scan Workflow

on: push

jobs:
    vuln_scan:
        name: Vulnerability scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Meterian scan
            uses: MeterianHQ/meterian-github-action@v1.0.2-canary
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                cli_args: --debug